version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update
      - echo Installing hugo
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.92.1/hugo_extended_0.92.1_Linux-64bit.deb
      - dpkg -i hugo.deb

  build:
    commands:
      - echo In build phase..
      - hugo --cleanDestinationDir --minify
      - hugo deploy --force
      - echo End of the build phase..
