baseURL = "https://muchas-glacias.com/"
languageCode = "fr-FR"
title = "Muchas Glacias - Testeur de site web écologique et accessible"
theme = "frozenTacos"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  title = "Muchas Glacias - Testeur de site web écologique et accessible"
  description = "Muchas Glacias est un testeur de site web sur l'écologie et l'accessibilité.\nCe testeur est développé par LABANQUI.SE"
  images = ["/img/pepper-index.png"]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
