baseURL = "https://muchas-glacias.com/"
languageCode = "fr-FR"
title = "Muchas Glacias - Testeur de site web écologique et accessible"
theme = "frozenTacos"
disableKinds = ["taxonomy", "taxonomyTerm"]
[params]
  title = "Muchas Glacias - Testeur de site web écologique et accessible"
  description = "Muchas Glacias est développé par LABANQUI.SE.\nTesteur de site web sur l'écologie et l'accessibilité"
  images = ["/img/pepper-index.png"]
  env = 'production'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[[deployment.targets]]
# An arbitrary name for this target.
name = "S3Deployment"
URL = "s3://muchas-glacias.com?region=eu-west-3&prefix=/"
cloudFrontDistributionID = "EF87VKWW0ND5D"